const NotificationActionTypes = {
  NOTIFICATION_ADD_START: 'NOTIFICATION_ADD_START',
  NOTIFICATION_ADD_SUCCESS: 'NOTIFICATION_ADD_SUCCESS',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
  NOTIFICATION_HIDE_START: 'NOTIFICATION_HIDE_START',
  NOTIFICATION_HIDE_SUCCESS: 'NOTIFICATION_HIDE_SUCCESS',
};

export default NotificationActionTypes;
