export const tracksdummy = [
  {
    id: 1,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/1.jpg',
  },
  {
    id: 2,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/ai.svg',
  },
  {
    id: 3,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/broadcast.svg',
  },
  {
    id: 4,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/music.svg',
  },
  {
    id: 5,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/play.svg',
  },
  {
    id: 6,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/playlist.svg',
  },
  {
    id: 7,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/ai.svg',
  },
  {
    id: 8,
    author: 'John Doe',
    name: 'Sample Track',
    genre: 'Sample',
    duration: '01:30',
    cover: '/images/1.jpg',
  },
];
