const MusicActionTypes = {
  ADD_TRACK_TO_PLAYLIST_START: 'ADD_TRACK_TO_PLAYLIST_START',
  ADD_TRACK_TO_PLAYLIST_END: 'ADD_TRACK_TO_PLAYLIST_END',
  PLAY_TRACK: 'PLAY_TRACK',
  PLAY_NEXT_TRACK: 'PLAY_NEXT_TRACK',
  PLAY_RADIO: 'PLAY_RADIO',
  EMPTY_SRC: 'EMPTY_SRC',
  DELETE_FROM_PLAYLIST: 'DELETE_FROM_PLAYLIST',
  CHANGE_PLAYING_STATE: 'CHANGE_PLAYING_STATE',
};

export default MusicActionTypes;
