const MusicActionTypes = {
  ADD_TRACK_TO_PLAYLIST_START: 'TOGGLE_CART_HIDDEN',
  ADD_TRACK_TO_PLAYLIST_END: 'ADD_ITEM',
  PLAY_TRACK: 'CLEAR_ITEM_FROM_CART',
  DELETE_FROM_PLAYLIST: 'REMOVE_ITEM',
};

export default MusicActionTypes;
